# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
    types: ["opened", "synchronize", "reopened"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install vim
        run: sudo apt-get install -y vim

      - name: Check vim version
        run: vim --version

      - name: Install .vimrc
        run: cp -f .vimrc ~
        
      - name: Run test scripts
        run: bash tests/run.sh

      - name: Show test log (toggle comment)
        if: ${{ always() }}
        run: cat tests/toggle_comments/test.log

